Sprint 1/step 1
DamirGuzaerov/react-burger pull request #1
Opened 2023-03-01 20:45 UTC by DamirGuzaerov

2023-03-02 10:35 UTC, flayexz requested changes
прекрасно

2023-03-02 10:55 UTC, TimurSadorov commented
Говнокодер

2023-03-02 11:11 UTC, LandyshH commented
Норм

2023-03-02 11:21 UTC, LipatovAlexander approved these changes
Отличная работа

2023-03-02 18:39 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная


* Верстка отличная

но есть некоторые недочеты: 

* Файл `App.test.js` нужно удалить, так как он не относится к проекту
* В консоли ошибки `key` https://disk.yandex.ru/i/oFVPQDz5aJyGZg 
* тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно
* При отрисовке **массива** компонентов нужно всегда указывать уникальный атрибут `key` в самом **верхнем** уровне верстки.




Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте **работоспособность проекта** и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 


Удачного рефакторинга кода.

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-constructor/burger-constructor.jsx
> +        "_id": PropTypes.string.isRequired,
тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-constructor/constructor-items/constructor-items.jsx
> +        "_id": PropTypes.string.isRequired,
тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-constructor/constructor-items/constructor-items.jsx
> +                    <li className={constructorItemsStyles['draggable-element']}>
При отрисовке **массива** компонентов нужно всегда указывать уникальный атрибут `key` в самом **верхнем** уровне верстки.

` key={ingredient._id}` нужно указывать тут в `li`

```jsx

                    <li  key={ingredient._id} className={constructorItemsStyles['draggable-element']}>

```

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-constructor/constructor-items/constructor-items.jsx
> +                            key={ingredient._id}
`key={ingredient._id}` тут не нужно

на 10й нужно

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        "_id": PropTypes.string,
* тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +        "_id": PropTypes.string,
* тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-ingredients/ingredients-group/ingredients-group.jsx
> +        "_id": PropTypes.string,
* тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2023-03-02 18:39 UTC, gennady-bars commented on src/components/burger-ingredients/ingredients-group/ingredients-group.jsx
> +                    return (<IngredientItem ingredient={el}/>)
При отрисовке **массива** компонентов нужно всегда указывать уникальный атрибут `key` в самом **верхнем** уровне верстки.



Для атрибута `key` лучше всего использовать уникальный `id` : у карточки как раз есть такой только с нижним подчеркиванием `_id`
[Почему индекс не нужно использовать, можно прочитать тут:]( https://medium.com/russian/%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%BA%D0%BB%D1%8E%D1%87%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8-%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-56bab8ada309)

2023-03-02 18:44 UTC, TimurSadorov commented
Чел, надо по FSD было сделать

2023-03-02 19:24 UTC, TimurSadorov commented
Чел используй ts

2023-03-02 19:27 UTC, DamirGuzaerov commented
> 

Всё будет, друг, но не сразу

2023-03-03 10:58 UTC, gennady-bars reviewed
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.


p.s. теперь нужно сделать 2й этап с попапами

* Внутри заказа не должно быть **других булок**: есть только верхняя и нижняя одинаковые.

2023-03-03 11:23 UTC, merged